"""Add payment number and reference number

Revision ID: 11a1580cf9d8
Revises: 4132b1b3e241
Create Date: 2025-09-06 17:53:00.539470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a1580cf9d8'
down_revision = '4132b1b3e241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reference_number', sa.String(length=100), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('reference_number')
        batch_op.drop_column('payment_number')

    # ### end Alembic commands ###
