"""Add final schema with all required columns and tables

Revision ID: e5b247e01907
Revises: 
Create Date: 2025-09-06 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b247e01907'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_order_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('disbursement_order_number', sa.String(length=100), nullable=True))

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('purchase_order_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('disbursement_order_number', sa.String(length=100), nullable=True))

    # Set a default for existing rows before making the column non-nullable
    op.execute("UPDATE invoice SET invoice_type = 'مستخلص مقاول' WHERE invoice_type IS NULL")

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('invoice_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_order_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('disbursement_order_number', sa.String(length=100), nullable=True))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reference_number', sa.String(length=100), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('reference_number')
        batch_op.drop_column('payment_number')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('disbursement_order_number')
        batch_op.drop_column('purchase_order_number')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('disbursement_order_number')
        batch_op.drop_column('purchase_order_number')
        batch_op.drop_column('invoice_type')

    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.drop_column('disbursement_order_number')
        batch_op.drop_column('purchase_order_number')
    # ### end Alembic commands ###